# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model1_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import pymysql

# Update
# -------------------------------------------------------------
# catch_conn = []
# --------------------------------------------------------------


class Ui_MainWindow(object):
    # Update: 連接資料庫
    # --------------------------------------------------------------
    # conn = pymysql.connect(host='localhost', port=3306, user='root',
    #                        password="", db="factorysystem")
    # catch_conn.append(conn)
    # --------------------------------------------------------------

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: #2D3142;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 50, 931, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #F5CB5C;")
        self.label.setObjectName("label")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(1420, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                                     "")
        self.close_btn.setObjectName("close_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1420, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAcceptDrops(False)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: #E5E5E5;")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1580, 40, 161, 91))
        self.lcdNumber.setStyleSheet("color: #e5e5e5;\n"
                                     "border-style: solid;\n"
                                     "border-width: 1px;\n"
                                     "border-color: #e5e5e5;")
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setDigitCount(3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(150, 110, 1621, 871))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setStyleSheet("border: none")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.tabBar().setStyleSheet(
            "QTabBar::tab{height: 50px; width: 200px;color: #768895;border-top-left-radius: 5px;border-top-right-radius: 5px}"
            "QTabBar::tab:selected{color: #E5E5E5;background-color: #546A7B;}")
        self.face_reg_tab = QtWidgets.QWidget()
        self.face_reg_tab.setStyleSheet(
            "border: none;background-color: #546A7B")
        self.face_reg_tab.setObjectName("face_reg_tab")
        self.face_reg_scr = QtWidgets.QLabel(self.face_reg_tab)
        self.face_reg_scr.setGeometry(QtCore.QRect(480, 30, 1024, 768))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.face_reg_scr.setFont(font)
        self.face_reg_scr.setStyleSheet("border-style: solid;\n"
                                        "border-width: 1px;\n"
                                        "border-color: #768895;\n"
                                        "")
        self.face_reg_scr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.face_reg_scr.setAlignment(QtCore.Qt.AlignCenter)
        self.face_reg_scr.setObjectName("face_reg_scr")
        self.gen_features_btn = QtWidgets.QPushButton(self.face_reg_tab)
        self.gen_features_btn.setGeometry(QtCore.QRect(110, 710, 301, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.gen_features_btn.setFont(font)
        self.gen_features_btn.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                                            "")
        self.gen_features_btn.setObjectName("gen_features_btn")
        self.face_reg_area = QtWidgets.QScrollArea(self.face_reg_tab)
        self.face_reg_area.setGeometry(QtCore.QRect(110, 450, 301, 231))
        self.face_reg_area.setMinimumSize(QtCore.QSize(0, 0))
        self.face_reg_area.setStyleSheet("background-color: #768895;")
        self.face_reg_area.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.face_reg_area.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.face_reg_area.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.face_reg_area.setWidgetResizable(True)
        self.face_reg_area.setObjectName("face_reg_area")
        self.face_reg_area.verticalScrollBar().setStyleSheet("QScrollBar:vertical"
                                                             "{width:12px;}"
                                                             "QScrollBar::handle:vertical"
                                                             "{width:12px;background:rgba(0,0,0,25%);min-height:20;}"
                                                             "QScrollBar::handle:vertical:hover"
                                                             "{width:12px;background:rgba(0,0,0,50%);min-height:20;}"
                                                             "QScrollBar::sub-line:vertical"
                                                             "{border: none;}"
                                                             "QScrollBar::add-line:vertical"
                                                             "{border: none;}"
                                                             "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical"
                                                             "{background:rgba(0,0,0,10%);}"
                                                             )
        self.face_reg_area.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal"
                                                            "{height:12px;}"
                                                            "QScrollBar::handle:horizontal"
                                                            "{height:12px;background:rgba(0,0,0,25%);min-width:20;}"
                                                            "QScrollBar::handle:horizontal:hover"
                                                            "{height:12px;background:rgba(0,0,0,50%);min-width:20;}"
                                                            "QScrollBar::sub-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.face_reg_contents = QtWidgets.QWidget()
        self.face_reg_contents.setGeometry(QtCore.QRect(0, 0, 301, 231))
        self.face_reg_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.face_reg_contents.setObjectName("face_reg_contents")
        self.face_reg_layout = QtWidgets.QVBoxLayout(self.face_reg_contents)
        self.face_reg_layout.setObjectName("face_reg_layout")
        self.face_reg_layout.setAlignment(QtCore.Qt.AlignTop)
        self.face_reg_area.setWidget(self.face_reg_contents)
        # 改
        self.verticalLayoutWidget = QtWidgets.QWidget(self.face_reg_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 59, 301, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.face_form_layout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.face_form_layout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.face_form_layout.setContentsMargins(0, 0, 0, 0)
        self.face_form_layout.setSpacing(3)
        self.face_form_layout.setObjectName("face_form_layout")
        self.form_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.form_title.setMaximumSize(QtCore.QSize(999, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.form_title.setFont(font)
        self.form_title.setStyleSheet("color: #FFF;")
        self.form_title.setAlignment(QtCore.Qt.AlignCenter)
        self.form_title.setObjectName("form_title")
        self.face_form_layout.addWidget(self.form_title)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setStyleSheet("background: #E5E5E5;\n"
                                "max-height: 1px;\n"
                                "border: none;\n"
                                "")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.face_form_layout.addWidget(self.line)
        self.id_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.id_title.setMinimumSize(QtCore.QSize(0, 0))
        self.id_title.setMaximumSize(QtCore.QSize(999, 30))
        self.id_title.setSizeIncrement(QtCore.QSize(0, 0))
        self.id_title.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id_title.setFont(font)
        self.id_title.setStyleSheet("color: #e5e5e5;")
        self.id_title.setObjectName("id_title")
        self.face_form_layout.addWidget(self.id_title)
        self.id_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.id_edit.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.id_edit.setFont(font)
        self.id_edit.setStyleSheet("background-color: #768895")
        self.id_edit.setObjectName("id_edit")
        self.face_form_layout.addWidget(self.id_edit)
        self.name_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name_title.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_title.setFont(font)
        self.name_title.setStyleSheet("color: #e5e5e5;")
        self.name_title.setObjectName("name_title")
        self.face_form_layout.addWidget(self.name_title)
        self.name_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name_edit.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.name_edit.setFont(font)
        self.name_edit.setStyleSheet("background-color: #768895")
        self.name_edit.setObjectName("name_edit")
        self.face_form_layout.addWidget(self.name_edit)
        self.email_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.email_title.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_title.setFont(font)
        self.email_title.setStyleSheet("color: #e5e5e5;")
        self.email_title.setObjectName("email_title")
        self.face_form_layout.addWidget(self.email_title)
        self.email_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email_edit.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.email_edit.setFont(font)
        self.email_edit.setStyleSheet("background-color: #768895")
        self.email_edit.setObjectName("email_edit")
        self.face_form_layout.addWidget(self.email_edit)
        self.identity_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.identity_title.setMaximumSize(QtCore.QSize(999, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.identity_title.setFont(font)
        self.identity_title.setStyleSheet("color: #e5e5e5;")
        self.identity_title.setObjectName("identity_title")
        self.face_form_layout.addWidget(self.identity_title)
        self.identity_edit = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.identity_edit.setMaximumSize(QtCore.QSize(999, 30))
        choices = ['作業人員', '管理人員', '外來訪客']
        self.identity_edit.addItems(choices)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.identity_edit.setFont(font)
        self.identity_edit.setStyleSheet("background-color: #768895")
        self.identity_edit.setMaxVisibleItems(10)
        self.identity_edit.setIconSize(QtCore.QSize(16, 16))
        self.identity_edit.setDuplicatesEnabled(False)
        self.identity_edit.setFrame(True)
        self.identity_edit.setObjectName("identity_edit")
        self.face_form_layout.addWidget(self.identity_edit)
        self.submit_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.submit_btn.setMaximumSize(QtCore.QSize(999, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submit_btn.setFont(font)
        self.submit_btn.setToolTip("")
        self.submit_btn.setToolTipDuration(0)
        self.submit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit_btn.setAutoFillBackground(False)
        self.submit_btn.setStyleSheet(
            "background-color: #e5e5e5; margin-top:10px;")
        self.submit_btn.setObjectName("submit_btn")
        self.face_form_layout.addWidget(self.submit_btn)
        self.tabWidget.addTab(self.face_reg_tab, "")
        self.face_tab = QtWidgets.QWidget()
        self.face_tab.setStyleSheet("border: none;background-color: #546A7B")
        self.face_tab.setObjectName("face_tab")
        self.face_scr = QtWidgets.QLabel(self.face_tab)
        self.face_scr.setGeometry(QtCore.QRect(480, 30, 1024, 768))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.face_scr.setFont(font)
        self.face_scr.setStyleSheet("border-style: solid;\n"
                                    "border-width: 1px;\n"
                                    "border-color: #768895;\n"
                                    "")
        self.face_scr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.face_scr.setAlignment(QtCore.Qt.AlignCenter)
        self.face_scr.setObjectName("face_scr")
        self.face_rec_label = QtWidgets.QLabel(self.face_tab)
        self.face_rec_label.setGeometry(QtCore.QRect(108, 50, 300, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.face_rec_label.setFont(font)
        self.face_rec_label.setStyleSheet(
            "color: #E5E5E5;margin-bottom:5px;border-bottom: 1px solid;border-bottom-color: #E5E5E5;")
        self.face_rec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.face_rec_label.setObjectName("face_rec_label")
        self.face_area = QtWidgets.QScrollArea(self.face_tab)
        self.face_area.setGeometry(QtCore.QRect(130, 110, 261, 645))
        self.face_area.setMinimumSize(QtCore.QSize(0, 0))
        self.face_area.setStyleSheet("background-color: #768895;")
        self.face_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.face_area.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.face_area.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.face_area.setWidgetResizable(True)
        self.face_area.setObjectName("face_area")
        self.face_area.verticalScrollBar().setStyleSheet("QScrollBar:vertical"
                                                         "{width:12px;}"
                                                         "QScrollBar::handle:vertical"
                                                         "{width:12px;background:rgba(0,0,0,25%);min-height:20;}"
                                                         "QScrollBar::handle:vertical:hover"
                                                         "{width:12px;background:rgba(0,0,0,50%);min-height:20;}"
                                                         "QScrollBar::sub-line:vertical"
                                                         "{border: none;}"
                                                         "QScrollBar::add-line:vertical"
                                                         "{border: none;}"
                                                         "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical"
                                                         "{background:rgba(0,0,0,10%);}"
                                                         )
        self.face_area.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal"
                                                        "{height:12px;}"
                                                        "QScrollBar::handle:horizontal"
                                                        "{height:12px;background:rgba(0,0,0,25%);min-width:20;}"
                                                        "QScrollBar::handle:horizontal:hover"
                                                        "{height:12px;background:rgba(0,0,0,50%);min-width:20;}"
                                                        "QScrollBar::sub-line:horizontal"
                                                        "{border: none;}"
                                                        "QScrollBar::add-line:horizontal"
                                                        "{border: none;}"
                                                        "QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal"
                                                        "{background:rgba(0,0,0,10%);}"
                                                        )
        self.face_area_contents = QtWidgets.QWidget()
        self.face_area_contents.setGeometry(QtCore.QRect(0, 0, 261, 681))
        self.face_area_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.face_area_contents.setObjectName("face_area_contents")
        self.face_layout = QtWidgets.QVBoxLayout(self.face_area_contents)
        self.face_layout.setObjectName("face_layout")
        self.face_layout.setAlignment(QtCore.Qt.AlignTop)
        self.face_area.setWidget(self.face_area_contents)
        self.tabWidget.addTab(self.face_tab, "")
        #-----------------------------------------------------------------
        self.face2_tab = QtWidgets.QWidget()
        self.face2_tab.setStyleSheet("border: none;background-color: #546A7B")
        self.face2_tab.setObjectName("face2_tab")
        self.face2_scr = QtWidgets.QLabel(self.face2_tab)
        self.face2_scr.setGeometry(QtCore.QRect(480, 30, 1024, 768))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.face2_scr.setFont(font)
        self.face2_scr.setStyleSheet("border-style: solid;\n"
                                    "border-width: 1px;\n"
                                    "border-color: #768895;\n"
                                    "")
        self.face2_scr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.face2_scr.setAlignment(QtCore.Qt.AlignCenter)
        self.face2_scr.setObjectName("face2_scr")
        self.face2_rec_label = QtWidgets.QLabel(self.face2_tab)
        self.face2_rec_label.setGeometry(QtCore.QRect(108, 50, 300, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.face2_rec_label.setFont(font)
        self.face2_rec_label.setStyleSheet(
            "color: #E5E5E5;margin-bottom:5px;border-bottom: 1px solid;border-bottom-color: #E5E5E5;")
        self.face2_rec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.face2_rec_label.setObjectName("face2_rec_label")
        self.face2_area = QtWidgets.QScrollArea(self.face2_tab)
        self.face2_area.setGeometry(QtCore.QRect(130, 110, 261, 645))
        self.face2_area.setMinimumSize(QtCore.QSize(0, 0))
        self.face2_area.setStyleSheet("background-color: #768895;")
        self.face2_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.face2_area.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.face2_area.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.face2_area.setWidgetResizable(True)
        self.face2_area.setObjectName("face2_area")
        self.face2_area.verticalScrollBar().setStyleSheet("QScrollBar:vertical"
                                                         "{width:12px;}"
                                                         "QScrollBar::handle:vertical"
                                                         "{width:12px;background:rgba(0,0,0,25%);min-height:20;}"
                                                         "QScrollBar::handle:vertical:hover"
                                                         "{width:12px;background:rgba(0,0,0,50%);min-height:20;}"
                                                         "QScrollBar::sub-line:vertical"
                                                         "{border: none;}"
                                                         "QScrollBar::add-line:vertical"
                                                         "{border: none;}"
                                                         "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical"
                                                         "{background:rgba(0,0,0,10%);}"
                                                         )
        self.face2_area.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal"
                                                        "{height:12px;}"
                                                        "QScrollBar::handle:horizontal"
                                                        "{height:12px;background:rgba(0,0,0,25%);min-width:20;}"
                                                        "QScrollBar::handle:horizontal:hover"
                                                        "{height:12px;background:rgba(0,0,0,50%);min-width:20;}"
                                                        "QScrollBar::sub-line:horizontal"
                                                        "{border: none;}"
                                                        "QScrollBar::add-line:horizontal"
                                                        "{border: none;}"
                                                        "QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal"
                                                        "{background:rgba(0,0,0,10%);}"
                                                        )
        self.face2_area_contents = QtWidgets.QWidget()
        self.face2_area_contents.setGeometry(QtCore.QRect(0, 0, 261, 681))
        self.face2_area_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.face2_area_contents.setObjectName("face2_area_contents")
        self.face2_layout = QtWidgets.QVBoxLayout(self.face2_area_contents)
        self.face2_layout.setObjectName("face2_layout")
        self.face2_layout.setAlignment(QtCore.Qt.AlignTop)
        self.face2_area.setWidget(self.face2_area_contents)
        self.tabWidget.addTab(self.face2_tab, "")
        #-----------------------------------------------------------------
        self.factory_tab = QtWidgets.QWidget()
        self.factory_tab.setStyleSheet(
            "border: none;background-color: #546A7B")
        self.factory_tab.setObjectName("factory_tab")
        self.factory_scr = QtWidgets.QLabel(self.factory_tab)
        self.factory_scr.setGeometry(QtCore.QRect(480, 30, 1024, 768))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.factory_scr.setFont(font)
        self.factory_scr.setStyleSheet("border-style: solid;\n"
                                       "border-width: 1px;\n"
                                       "border-color: #768895;\n"
                                       "")
        self.factory_scr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.factory_scr.setAlignment(QtCore.Qt.AlignCenter)
        self.factory_scr.setObjectName("factory_scr")
        self.factory_rec_label = QtWidgets.QLabel(self.factory_tab)
        self.factory_rec_label.setGeometry(QtCore.QRect(108, 50, 300, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.factory_rec_label.setFont(font)
        self.factory_rec_label.setStyleSheet(
            "color: #E5E5E5;margin-bottom:5px;border-bottom: 1px solid;border-bottom-color: #E5E5E5;")
        self.factory_rec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.factory_rec_label.setObjectName("factory_rec_label")
        self.factory_area = QtWidgets.QScrollArea(self.factory_tab)
        self.factory_area.setGeometry(QtCore.QRect(130, 110, 261, 645))
        self.factory_area.setMinimumSize(QtCore.QSize(0, 0))
        self.factory_area.setStyleSheet("background-color: #768895;")
        self.factory_area.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.factory_area.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.factory_area.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.factory_area.setWidgetResizable(True)
        self.factory_area.setObjectName("factory_area")
        self.factory_area.verticalScrollBar().setStyleSheet("QScrollBar:vertical"
                                                            "{width:12px;}"
                                                            "QScrollBar::handle:vertical"
                                                            "{width:12px;background:rgba(0,0,0,25%);min-height:20;}"
                                                            "QScrollBar::handle:vertical:hover"
                                                            "{width:12px;background:rgba(0,0,0,50%);min-height:20;}"
                                                            "QScrollBar::sub-line:vertical"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:vertical"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.factory_area.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal"
                                                            "{height:12px;}"
                                                            "QScrollBar::handle:horizontal"
                                                            "{height:12px;background:rgba(0,0,0,25%);min-width:20;}"
                                                            "QScrollBar::handle:horizontal:hover"
                                                            "{height:12px;background:rgba(0,0,0,50%);min-width:20;}"
                                                            "QScrollBar::sub-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.fatory_contents = QtWidgets.QWidget()
        self.fatory_contents.setGeometry(QtCore.QRect(0, 0, 261, 681))
        self.fatory_contents.setMinimumSize(QtCore.QSize(0, 0))
        self.fatory_contents.setObjectName("fatory_contents")
        self.factory_layout = QtWidgets.QVBoxLayout(self.fatory_contents)
        self.factory_layout.setObjectName("factory_layout")
        self.factory_layout.setAlignment(QtCore.Qt.AlignTop)
        self.factory_area.setWidget(self.fatory_contents)
        self.tabWidget.addTab(self.factory_tab, "")
        self.score_tab = QtWidgets.QWidget()
        self.score_tab.setStyleSheet("border: none;background-color: #546A7B")
        self.score_tab.setObjectName("score_tab")
        self.score_table = QtWidgets.QTableWidget(self.score_tab)
        self.score_table.setGeometry(QtCore.QRect(105, 40, 1413, 671))
        self.score_table.setSelectionBehavior(1)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.score_table.setFont(font)
        self.score_table.setStyleSheet("background: #768895;")
        self.score_table.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.score_table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.score_table.setAutoScroll(True)
        self.score_table.setAutoScrollMargin(16)
        self.score_table.setTabKeyNavigation(True)
        self.score_table.setProperty("showDropIndicator", True)
        self.score_table.setGridStyle(QtCore.Qt.SolidLine)
        self.score_table.setWordWrap(True)
        self.score_table.setCornerButtonEnabled(True)
        self.score_table.setRowCount(0)
        self.score_table.setObjectName("score_table")
        self.score_table.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.score_table.setHorizontalHeaderItem(6, item)
        self.score_table.horizontalHeader().setVisible(True)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        font.setBold(True)
        self.score_table.horizontalHeader().setFont(font)
        self.score_table.horizontalHeader().setFixedHeight(40)
        self.score_table.setColumnWidth(0, 200)
        self.score_table.setColumnWidth(1, 150)
        self.score_table.setColumnWidth(2, 400)
        self.score_table.setColumnWidth(3, 250)
        self.score_table.setColumnWidth(4, 200)
        self.score_table.setColumnWidth(5, 100)
        self.score_table.setColumnWidth(6, 100)
        self.score_table.horizontalHeader().setHighlightSections(True)
        self.score_table.horizontalHeader().setMinimumSectionSize(20)
        self.score_table.horizontalHeader().setSortIndicatorShown(False)
        self.score_table.horizontalHeader().setStretchLastSection(False)
        self.score_table.verticalHeader().setVisible(False)
        self.score_table.verticalHeader().setDefaultSectionSize(40)
        self.score_table.verticalHeader().setMinimumSectionSize(25)
        self.score_table.verticalScrollBar().setStyleSheet("QScrollBar:vertical"
                                                            "{width:12px;}"
                                                            "QScrollBar::handle:vertical"
                                                            "{width:12px;background:rgba(0,0,0,25%);min-height:20;}"
                                                            "QScrollBar::handle:vertical:hover"
                                                            "{width:12px;background:rgba(0,0,0,50%);min-height:20;}"
                                                            "QScrollBar::sub-line:vertical"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:vertical"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.score_table.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal"
                                                            "{height:12px;}"
                                                            "QScrollBar::handle:horizontal"
                                                            "{height:12px;background:rgba(0,0,0,25%);min-width:20;}"
                                                            "QScrollBar::handle:horizontal:hover"
                                                            "{height:12px;background:rgba(0,0,0,50%);min-width:20;}"
                                                            "QScrollBar::sub-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.score_delete_btn = QtWidgets.QPushButton(self.score_tab)
        self.score_delete_btn.setGeometry(QtCore.QRect(1359, 730, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.score_delete_btn.setFont(font)
        self.score_delete_btn.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                                            "")
        self.score_delete_btn.setObjectName("score_delete_btn")
        self.tabWidget.addTab(self.score_tab, "")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setStyleSheet("border: none;background-color: #546A7B")
        self.io_tab.setObjectName("io_tab")
        self.io_table = QtWidgets.QTableWidget(self.io_tab)
        self.io_table.setGeometry(QtCore.QRect(300, 40, 1013, 671))
        self.io_table.setSelectionBehavior(1)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.io_table.setFont(font)
        self.io_table.setStyleSheet("background: #768895;")
        self.io_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.io_table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.io_table.setAutoScroll(True)
        self.io_table.setAutoScrollMargin(16)
        self.io_table.setTabKeyNavigation(True)
        self.io_table.setProperty("showDropIndicator", True)
        self.io_table.setGridStyle(QtCore.Qt.SolidLine)
        self.io_table.setWordWrap(True)
        self.io_table.setCornerButtonEnabled(True)
        self.io_table.setRowCount(0)
        self.io_table.setObjectName("io_table")
        self.io_table.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.io_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.io_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.io_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.io_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.io_table.setHorizontalHeaderItem(4, item)
        self.io_table.horizontalHeader().setVisible(True)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        font.setBold(True)
        self.io_table.horizontalHeader().setFont(font)
        self.io_table.horizontalHeader().setFixedHeight(40)
        self.io_table.horizontalHeader().setCascadingSectionResizes(False)
        self.io_table.setColumnWidth(0, 200)
        self.io_table.setColumnWidth(1, 150)
        self.io_table.setColumnWidth(2, 150)
        self.io_table.setColumnWidth(3, 250)
        self.io_table.setColumnWidth(4, 250)
        self.io_table.horizontalHeader().setHighlightSections(True)
        self.io_table.horizontalHeader().setMinimumSectionSize(20)
        self.io_table.horizontalHeader().setSortIndicatorShown(False)
        self.io_table.horizontalHeader().setStretchLastSection(False)
        self.io_table.verticalHeader().setVisible(False)
        self.io_table.verticalHeader().setCascadingSectionResizes(False)
        self.io_table.verticalHeader().setDefaultSectionSize(40)
        self.io_table.verticalHeader().setMinimumSectionSize(25)
        self.io_table.verticalScrollBar().setStyleSheet("QScrollBar:vertical"
                                                            "{width:12px;}"
                                                            "QScrollBar::handle:vertical"
                                                            "{width:12px;background:rgba(0,0,0,25%);min-height:20;}"
                                                            "QScrollBar::handle:vertical:hover"
                                                            "{width:12px;background:rgba(0,0,0,50%);min-height:20;}"
                                                            "QScrollBar::sub-line:vertical"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:vertical"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.io_table.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal"
                                                            "{height:12px;}"
                                                            "QScrollBar::handle:horizontal"
                                                            "{height:12px;background:rgba(0,0,0,25%);min-width:20;}"
                                                            "QScrollBar::handle:horizontal:hover"
                                                            "{height:12px;background:rgba(0,0,0,50%);min-width:20;}"
                                                            "QScrollBar::sub-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-line:horizontal"
                                                            "{border: none;}"
                                                            "QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal"
                                                            "{background:rgba(0,0,0,10%);}"
                                                            )
        self.io_delete_btn = QtWidgets.QPushButton(self.io_tab)
        self.io_delete_btn.setGeometry(QtCore.QRect(1150, 730, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.io_delete_btn.setFont(font)
        self.io_delete_btn.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                                         "")
        self.io_delete_btn.setObjectName("io_delete_btn")
        self.tabWidget.addTab(self.io_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # Update: 讀取資料
        # -------------------------------------------------------------
        # self.OpenForm()
        # -------------------------------------------------------------
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 人臉註冊訊息
        # for i in range(10):
        #     label = QtWidgets.QLabel("測試訊息")
        #     label.setStyleSheet("font-size:16px; font-family: 微軟正黑體;")
        #     self.face_reg_layout.addWidget(label)

        # 人臉辨識訊息
        # for i in range(10):
        #     widget = QtWidgets.QWidget()
        #     widget.setFixedSize(243, 100)
        #     widget.setStyleSheet("background-color: #91A0AA")
        #     layout = QtWidgets.QGridLayout()
        #     label1 = QtWidgets.QLabel("辨識項目")
        #     label1.setStyleSheet(
        #         "color: #000000; font-size:20px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label1, 0, 0)
        #     label2 = QtWidgets.QLabel("員工編號")
        #     label2.setStyleSheet(
        #         "color: #000000; background-color: #768895;padding-left: 5; font-size:16px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label2, 0, 1)
        #     label3 = QtWidgets.QLabel("日期\n時間")
        #     label3.setStyleSheet(
        #         "color: #000000; font-size: 14px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label3, 1, 0)
        #     label4 = QtWidgets.QLabel("員工姓名")
        #     label4.setStyleSheet(
        #         "color: #000000; background-color: #768895;padding-left: 5; font-size:16px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label4, 1, 1)
        #     widget.setLayout(layout)
        #     self.face_layout.addWidget(widget)

        # 工廠辨識訊息
        # for i in range(10):
        #     widget = QtWidgets.QWidget()
        #     widget.setFixedSize(243, 100)
        #     widget.setStyleSheet("background-color: #91A0AA")
        #     layout = QtWidgets.QGridLayout()
        #     label1 = QtWidgets.QLabel("辨識項目")
        #     label1.setStyleSheet(
        #         "color: #000000; font-size:20px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label1, 0, 0)
        #     label2 = QtWidgets.QLabel("員工編號")
        #     label2.setStyleSheet(
        #         "color: #000000; background-color: #768895;padding-left: 5; font-size:16px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label2, 0, 1)
        #     label3 = QtWidgets.QLabel("日期\n時間")
        #     label3.setStyleSheet(
        #         "color: #000000; font-size: 14px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label3, 1, 0)
        #     label4 = QtWidgets.QLabel("員工姓名")
        #     label4.setStyleSheet(
        #         "color: #000000; background-color: #768895;padding-left: 5; font-size:16px; font-weight:bold; font-family: 微軟正黑體;")
        #     layout.addWidget(label4, 1, 1)
        #     widget.setLayout(layout)
        #     self.factory_layout.addWidget(widget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "工廠安全之員工服儀智慧辨識系統"))
        self.label.setText(_translate("MainWindow", "time"))
        self.close_btn.setText(_translate("MainWindow", "關閉系統"))
        self.label_3.setText(_translate("MainWindow", "登入管理者"))
        self.face_reg_scr.setText(_translate("MainWindow", "Monitor screen"))
        self.gen_features_btn.setText(_translate("MainWindow", "擷取特徵"))
        # 改
        self.form_title.setText(_translate("MainWindow", "新進員工資料登錄"))
        self.id_title.setText(_translate("MainWindow", "員工編號"))
        self.name_title.setText(_translate("MainWindow", "員工姓名"))
        self.email_title.setText(_translate("MainWindow", "電子信箱"))
        self.identity_title.setText(_translate("MainWindow", "所屬身分"))
        self.submit_btn.setText(_translate("MainWindow", "登錄資料"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.face_reg_tab), _translate("MainWindow", "人臉註冊"))
        self.face_scr.setText(_translate("MainWindow", "Monitor screen"))
        self.face_rec_label.setText(_translate("MainWindow", "入口辨識紀錄"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.face_tab), _translate("MainWindow", "入口辨識"))
        #--------------------------------------------------------
        self.face2_scr.setText(_translate("MainWindow", "Monitor screen"))
        self.face2_rec_label.setText(_translate("MainWindow", "出口辨識紀錄"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.face2_tab), _translate("MainWindow", "出口辨識"))
        #--------------------------------------------------------
        self.factory_scr.setText(_translate("MainWindow", "Monitor screen"))
        self.factory_rec_label.setText(_translate("MainWindow", "安全辨識紀錄"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.factory_tab), _translate("MainWindow", "安全辨識"))
        self.score_table.setSortingEnabled(False)
        item = self.score_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "人員編號"))
        item = self.score_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "人員姓名"))
        item = self.score_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "照片編號"))
        item = self.score_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "扣除時間"))
        item = self.score_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "扣分項目"))
        item = self.score_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "扣除分數"))
        item = self.score_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "人員總分"))
        self.score_delete_btn.setText(_translate("MainWindow", "刪除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.score_tab), _translate("MainWindow", "分數紀錄表"))
        self.io_table.setSortingEnabled(False)
        item = self.io_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "人員編號"))
        item = self.io_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "人員姓名"))
        item = self.io_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "人員身分"))
        item = self.io_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "進廠時間"))
        item = self.io_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "出廠時間"))
        self.io_delete_btn.setText(_translate("MainWindow", "刪除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.io_tab), _translate("MainWindow", "進出紀錄表"))
        # Update: 刪除按鈕事件
        # -------------------------------------------------------------
        # self.io_delete_btn.clicked.connect(self.io_Delete)
        # self.score_delete_btn.clicked.connect(self.score_Delete)
        # -------------------------------------------------------------
        # Update2.0: 新增按鈕事件
        # -------------------------------------------------------------
        # self.submit_btn.clicked.connect(self.member_add)
        # -------------------------------------------------------------

    # Update: 讀取資料
    # -------------------------------------------------------------

    # def OpenForm(self):
    #     cur = catch_conn[0].cursor()
    #     # 讀取進出紀錄表
    #     sql = "SELECT * FROM face"
    #     cur.execute(sql)
    #     data = cur.fetchall()
    #     x = 0
    #     for i in data:
    #         row_num = self.io_table.rowCount()
    #         self.io_table.setRowCount(row_num+1)
    #         y = 0
    #         for j in i:
    #             item = QtWidgets.QTableWidgetItem(str(data[x][y]))
    #             item.setTextAlignment(
    #                 QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
    #             self.io_table.setItem(x, y, item)
    #             y += 1
    #         x += 1
    #     # 讀取分數紀錄表
    #     sql = "SELECT * FROM safeidentify"
    #     cur.execute(sql)
    #     data = cur.fetchall()
    #     x = 0
    #     for i in data:
    #         row_num = self.score_table.rowCount()
    #         self.score_table.setRowCount(row_num+1)
    #         y = 0
    #         for j in i:
    #             item = QtWidgets.QTableWidgetItem(str(data[x][y]))
    #             item.setTextAlignment(
    #                 QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
    #             self.score_table.setItem(x, y, item)
    #             y += 1
    #         x += 1
    # # -------------------------------------------------------------

    # # Update: 刪除事件
    # # -------------------------------------------------------------
    # # 刪除進出紀錄
    # def io_Delete(self, MainWindow):
    #     cur = catch_conn[0].cursor()
    #     try:
    #         row_2 = self.io_table.currentRow()
    #         del_d = self.io_table.item(row_2, 3).text()
    #         cur.execute("DELETE FROM face WHERE EnterTime = '"+del_d+"'")
    #         catch_conn[0].commit()
    #         self.io_table.removeRow(row_2)
    #     except:
    #         pass

    # # 刪除辨識紀錄
    # def score_Delete(self, MainWindow):
    #     cur = catch_conn[0].cursor()
    #     try:
    #         row_2 = self.score_table.currentRow()
    #         del_d = self.score_table.item(row_2, 3).text()
    #         cur.execute(
    #             "DELETE FROM safeidentify WHERE LoseTime = '"+del_d+"'")
    #         catch_conn[0].commit()
    #         self.score_table.removeRow(row_2)
    #     except:
    #         pass
    # # -------------------------------------------------------------

    # Update2.0: 新增事件
    # -------------------------------------------------------------
    # def member_add(self, MainWindow):
    #     db_id = self.id_edit.text()
    #     db_name = self.name_edit.text()
    #     db_email = self.email_edit.text()
    #     db_identity = self.identity_edit.currentText()
    #     catch_conn[0].cursor().execute("INSERT INTO `member` (`id`, `name`,`email`,`score`,`identity`) VALUES ('" +
    #                                    str(db_id)+"', '"+str(db_name)+"', '"+str(db_email)+"', 100, '"+str(db_identity)+"')")
    #     catch_conn[0].commit()
    # -------------------------------------------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
